project_name: rewinged

builds:
  - id: windows
    hooks:
      pre:
        - ./template-versioninfo.sh '{{ time "2006" }}' "{{ .Version }}" "{{ .Major }}" "{{ .Minor }}" "{{ .Patch }}"
        - go generate # creates versioninfo resource file used by windows build
      post:
        - '/bin/sh -c "rm resource.syso || true"' # ensure resource file meant for windows is gone or it leads to 'architecture incompatible' compile error on linux
    ldflags:
      - -s -w # do not include debug symbols in executables
      - -X 'main.version={{.Version}}' # set version information in-program
      - -X 'main.commit={{.ShortCommit}}' # set commit information in-program
      - -X 'main.compileTime={{.Date}}' # set timestamp information in-program
      - -X 'main.releaseMode=true' # set gin to releaseMode
    goos: [windows]
    goarch: [amd64]
    goamd64: [v1]
  - id: linux
    hooks:
      pre:
        - '/bin/sh -c "rm resource.syso || true"' # ensure resource file meant for windows is gone or it leads to 'architecture incompatible' compile error
    ldflags:
      - -s -w # do not include debug symbols in executables
      - -X 'main.version={{.Version}}' # set version information in-program
      - -X 'main.commit={{.ShortCommit}}' # set commit information in-program
      - -X 'main.compileTime={{.Date}}' # set timestamp information in-program
      - -X 'main.releaseMode=true' # set gin to releaseMode
    goos: [linux]
    goarch: [amd64]
    goamd64: [v1]

archives:
  - format: zip

changelog:
  filters:
    exclude:
      - '^(?i)ci:'
      - '^(?i)readme:'

release:
  name_template: "Version {{.Version}}"
  draft: true

dockers:
  - id: linux
    ids:
    - linux

    # don't push rc images
    # skip_push: auto

    image_templates:
    - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:latest
    - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{.Major}}.{{.Minor}}
    - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{.Version}}

    # Set the "backend" for the Docker pipe.
    #
    # Valid options are: docker, buildx, podman.
    #
    # Podman is a GoReleaser Pro feature and is only available on Linux.
    #
    # Defaults to docker.
    use: docker

    build_flag_templates:
    - --pull
    - --label=org.opencontainers.image.created={{.Date}}
    - --label=org.opencontainers.image.title={{.ProjectName}}
    - --label=org.opencontainers.image.revision={{.FullCommit}}
    - --label=org.opencontainers.image.version={{.Version}}
    # - "--platform=linux/arm64"
